import {
  faFileCode,
  faFileImage,
  faFilePdf,
  faFileAudio,
  faFileVideo,
  faFileAlt,
  faFileCsv,
} from "@fortawesome/free-solid-svg-icons";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const mimeTypeIcons: { [key: string]: IconDefinition } = {
  JavaScript: faFileCode,
  TypeScript: faFileCode,
  Python: faFileCode,
  Java: faFileCode,
  C: faFileCode,
  "C++": faFileCode,
  Ruby: faFileCode,
  PHP: faFileCode,
  HTML: faFileCode,
  CSS: faFileCode,
  "Shell Script": faFileCode,
  Perl: faFileCode,
  Kotlin: faFileCode,
  Go: faFileCode,
  SQL: faFileCode,
  MATLAB: faFileCode,
  Haskell: faFileCode,
  Lua: faFileCode,
  Scala: faFileCode,
  Text: faFileAlt,
  "JPEG Image": faFileImage,
  "PNG Image": faFileImage,
  "GIF Image": faFileImage,
  "PDF Document": faFilePdf,
  "MP3 Audio": faFileAudio,
  "MP4 Video": faFileVideo,
  "SVG Image": faFileImage,
  CSV: faFileCsv,
};

export const mimeTypes: { [key: string]: string } = {
  "application/javascript": "JavaScript",
  "application/typescript": "TypeScript",
  "text/x-python": "Python",
  "text/x-java-source": "Java",
  "text/x-c": "C",
  "text/x-c++src": "C++",
  "application/x-ruby": "Ruby",
  "application/x-httpd-php": "PHP",
  "text/html": "HTML",
  "text/css": "CSS",
  "application/x-sh": "Shell Script",
  "application/x-perl": "Perl",
  "text/x-kotlin": "Kotlin",
  "text/x-go": "Go",
  "application/sql": "SQL",
  "text/x-matlab": "MATLAB",
  "text/x-haskell": "Haskell",
  "text/x-lua": "Lua",
  "text/x-scala": "Scala",
  "text/plain": "Text",
  "image/jpeg": "JPEG Image",
  "image/png": "PNG Image",
  "image/gif": "GIF Image",
  "application/pdf": "PDF Document",
  "audio/mpeg": "MP3 Audio",
  "video/mp4": "MP4 Video",
  "image/svg+xml": "SVG Image",
  "text/csv": "CSV",
};
